# Dockerfile.data-ingestion
FROM python:3.9-slim

WORKDIR /app

# Copy file requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy toàn bộ source code vào container
COPY src/ ./src/

# Thiết lập PYTHONPATH để Python nhận diện được module 'src'
ENV PYTHONPATH="${PYTHONPATH}:/app"
ENV PYTHONUNBUFFERED=1

# Lệnh chạy mặc định
CMD ["python", "src/data_ingestion/stock_api_consumer.py"]