# Dockerfile.data-ingestion
FROM python:3.9-slim

WORKDIR /app

# Copy file requirements.txt (Tạo file này nếu chưa có: chứa dòng "kafka-python" và "requests")
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY src/ ./src/
CMD ["python", "/app/src/data_ingestion/stock_api_consumer.py"]