# Dockerfile.dashboard
FROM python:3.9-slim

WORKDIR /app

# Cài đặt các thư viện cần thiết
RUN pip install streamlit pymongo pandas plotly

# Copy code vào container
COPY src/dashboard /app/src/dashboard

# Mở port 8051
EXPOSE 8051
CMD ["streamlit", "run", "src/dashboard/app.py", "--server.port", "8051", "--server.address", "0.0.0.0"]